apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: crc-performance-turning
  namespace: NAMESPACE_TO_REPLACE
spec:
  selector:
   matchExpressions:
    - {key: environment, operator: NotIn, values: [dev]}
  env:
    - name: "GODEBUG"
      value: "madvdontneed=1"
    - name: "GOGC"
      value: "10"
